{% set name = "graphene-django" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b78c9b05bc899016b9cc5bf13faa1f37fe1faa8c5407552c6ddd1a28f46fc31a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - pytest-runner
  run:
    - django >=1.11
    - graphene >=2.1.7,<3
    - graphql-core >=2.1.0,<3
    - promise >=2.1
    - python >=2.7
    - singledispatch >=3.4.0.3
    - six >=1.10.0
    - text-unidecode

about:
  home: https://github.com/graphql-python/graphene-django
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Graphene Django integration
  description: Graphene-Django is built on top of Graphene. Graphene-Django provides some additional abstractions that make it easy to add GraphQL functionality to your Django project.
  doc_url: https://docs.graphene-python.org/projects/django/en/latest/
  dev_url: https://github.com/graphql-python/graphene-django

extra:
  recipe-maintainers:
    - rxm7706
    - KingDarBoja
